/* ============================================================
   config.js — App Configuration & Translations
   GPA Calculator v2.0
   ============================================================ */
'use strict';

const APP_VERSION = '2.0';
const DEFAULT_SUBJECTS = 6;
const MAX_HOURS = 6;      // أقصى ساعات لمادة واحدة
const MAX_DEGREE = 100;

/* ── Grading Systems ─────────────────────────── */
const GRADING_SYSTEMS = {
    '4.0': [
        { min: 90, points: 4.000, grade: 'A+' },
        { min: 85, points: 3.667, grade: 'A'  },
        { min: 80, points: 3.333, grade: 'B+' },
        { min: 75, points: 3.000, grade: 'B'  },
        { min: 70, points: 2.667, grade: 'C+' },
        { min: 65, points: 2.333, grade: 'C'  },
        { min: 60, points: 2.000, grade: 'D'  },
        { min:  0, points: 0.000, grade: 'F'  },
    ],
    '5.0': [
        { min: 95, points: 5.000, grade: 'A+' },
        { min: 90, points: 4.500, grade: 'A'  },
        { min: 85, points: 4.000, grade: 'B+' },
        { min: 80, points: 3.500, grade: 'B'  },
        { min: 75, points: 3.000, grade: 'C+' },
        { min: 70, points: 2.500, grade: 'C'  },
        { min: 65, points: 2.000, grade: 'D'  },
        { min:  0, points: 0.000, grade: 'F'  },
    ],
};

/* ── Translations ────────────────────────────── */
const TRANSLATIONS = {
    ar: {
        title:                    'حاسبة المعدل التراكمي',
        description:              'احسب معدلك الدراسي بسهولة ودقة',
        previousCumulative:       'البيانات التراكمية السابقة',
        previousCumulativeTip:    'أدخل بياناتك التراكمية السابقة لتضمينها في المعدل الكلي',
        cumulativeTerm:           'المعدل التراكمي الكلي',
        cumulativeTermTip:        'يعرض هذا القسم المعدل التراكمي الكلي بناءً على جميع الفصول',
        termResult:               'الفصل',
        total:                    'المجموع',
        percentage:               'النسبة',
        grade:                    'التقدير',
        points:                   'النقاط',
        hours:                    'الساعات المجتازة',
        totalHours:               'الساعات الكلية',
        subjectName:              'اسم المقرر',
        degree:                   'الدرجة',
        addTerm:                  'إضافة فصل دراسي',
        exportPDF:                'تصدير PDF',
        exportExcel:              'تصدير Excel',
        reset:                    'إعادة تعيين',
        share:                    'مشاركة',
        deleteTerm:               'حذف الفصل',
        addSubject:               'إضافة مادة',
        notSpecified:             'غير محدد',
        statistics:               'إحصائيات المعدل',
        comparison:               'مقارنة الفصول',
        tips:                     'نصائح لتحسين معدلك',
        tip1:                     'ركّز على المواد ذات الساعات الأعلى لأنها تؤثر بشكل أكبر على المعدل.',
        tip2:                     'حاول تحسين درجاتك في المواد التي حصلت فيها على تقدير منخفض.',
        tip3:                     'نظّم وقتك جيداً لمراجعة جميع المواد قبل الامتحانات.',
        bestSubject:              'أفضل مادة',
        worstSubject:             'أضعف مادة',
        bestTerm:                 'أفضل فصل',
        worstTerm:                'أضعف فصل',
        invalidDegree:            'الدرجة يجب أن تكون بين 0 و 100',
        invalidHours:             'الساعات يجب أن تكون بين 0.5 و 6',
        invalidPercentage:        'النسبة يجب أن تكون بين 0 و 100',
        invalidPoints:            'النقاط يجب أن تكون بين 0 و {max}',
        exportSuccess:            'تم التصدير بنجاح!',
        resetSuccess:             'تم إعادة التعيين',
        shareMessage:             'نتائج معدلي التراكمي:',
        shareError:               'تعذّرت المشاركة',
        copySuccess:              'تم النسخ إلى الحافظة',
        gradingSystem:            'نظام الدرجات',
        gradingSystem40:          'نظام 4.0',
        gradingSystem50:          'نظام 5.0',
        prevPercentagePH:         'النسبة التراكمية السابقة',
        prevPointsPH:             'النقاط التراكمية السابقة',
        prevHoursPH:              'الساعات المجتازة السابقة',
        subjectPH:                'مقرر',
        hoursPH:                  'الساعات',
        degreePH:                 'الدرجة',
        bylawFail:                'راسب لائحة',
        normalFail:               'راسب',
        pass:                     'ناجح',
        noTerms:                  'لا توجد فصول بعد',
    },
    en: {
        title:                    'GPA Calculator',
        description:              'Calculate your GPA easily and accurately',
        previousCumulative:       'Previous Cumulative Data',
        previousCumulativeTip:    'Enter previous cumulative data to include in the overall GPA',
        cumulativeTerm:           'Overall Cumulative GPA',
        cumulativeTermTip:        'This section shows the overall cumulative GPA across all terms',
        termResult:               'Term',
        total:                    'Total',
        percentage:               'Percentage',
        grade:                    'Grade',
        points:                   'GPA Points',
        hours:                    'Credit Hours',
        totalHours:               'Total Hours',
        subjectName:              'Course Name',
        degree:                   'Score',
        addTerm:                  'Add Term',
        exportPDF:                'Export PDF',
        exportExcel:              'Export Excel',
        reset:                    'Reset',
        share:                    'Share',
        deleteTerm:               'Delete Term',
        addSubject:               'Add Course',
        notSpecified:             'Not specified',
        statistics:               'GPA Statistics',
        comparison:               'Term Comparison',
        tips:                     'Tips to Improve Your GPA',
        tip1:                     'Focus on courses with higher credit hours as they impact your GPA more.',
        tip2:                     'Improve your grades in courses where you scored low.',
        tip3:                     'Organize your time to review all subjects before exams.',
        bestSubject:              'Best Course',
        worstSubject:             'Weakest Course',
        bestTerm:                 'Best Term',
        worstTerm:                'Weakest Term',
        invalidDegree:            'Score must be between 0 and 100',
        invalidHours:             'Hours must be between 0.5 and 6',
        invalidPercentage:        'Percentage must be between 0 and 100',
        invalidPoints:            'Points must be between 0 and {max}',
        exportSuccess:            'Exported successfully!',
        resetSuccess:             'Data reset',
        shareMessage:             'My Cumulative GPA Results:',
        shareError:               'Failed to share',
        copySuccess:              'Copied to clipboard',
        gradingSystem:            'Grading System',
        gradingSystem40:          '4.0 System',
        gradingSystem50:          '5.0 System',
        prevPercentagePH:         'Previous cumulative percentage',
        prevPointsPH:             'Previous cumulative points',
        prevHoursPH:              'Previous credit hours passed',
        subjectPH:                'Course',
        hoursPH:                  'Hours',
        degreePH:                 'Score',
        bylawFail:                'Bylaw Fail',
        normalFail:               'Fail',
        pass:                     'Pass',
        noTerms:                  'No terms yet',
    },
};
